### ISSUE TITLE
@mahmod87

### ISSUE THREAD

**Issue by IMOLE10** [mahmod87/MINI-MARKIT#3]
_Originally posted by @mahmod87   in https://github.com/mahmod87/MINI-MARKIT/issues/1#issuecomment-1606146817_

**Comment by IMOLE10** [comment]
> ```
>           @mahmod87
> ```
> 
> 
>     
>  
>   
> 
> _Originally posted by @IMOLE10 in [#1 (comment)](https://github.com/mahmod87/MINI-MARKIT/issues/1#issuecomment-1606146817)_

**Comment by mahmod87** [comment]
05
